# Generated by Django 3.2 on 2022-09-07 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=60, unique=True, verbose_name='Адрес площадки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places', verbose_name='Фото площадки')),
                ('kind_sport', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Волейбол', 'Волейбол'), ('Футбол', 'Футбол')], max_length=20, verbose_name='Вид спорта')),
                ('descr', models.TextField(verbose_name='Описание площадки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('open_hours', models.TextField(default='00:00-00:00', max_length=11, verbose_name='Время работы')),
                ('city', models.CharField(default='Минск', max_length=20, verbose_name='Город')),
                ('type_pg', models.CharField(choices=[('Открытый', 'Открытый'), ('Закрытый', 'Закрытый')], max_length=20, verbose_name='Тип площадки')),
                ('coating', models.CharField(max_length=20, verbose_name='Покрытие')),
                ('avrg_capacity', models.CharField(choices=[('0-50', '0-50 человек'), ('50-100', '50-100 человек'), ('+100', '100+ человек')], max_length=20, verbose_name='Средняя вместимость')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
