# Generated by Django 3.2 on 2022-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_remove_place_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='open_hours',
            field=models.TextField(default='00:00-00:00', max_length=11, verbose_name='Время работы'),
        ),
    ]
