# Generated by Django 3.2 on 2022-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='close_hours',
            field=models.TimeField(default='00:00', verbose_name='Часы закрытия'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_hours',
            field=models.TimeField(default='00:00', verbose_name='Часы открытия'),
        ),
    ]
