# Generated by Django 3.2 on 2022-09-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0003_place_open_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='close_hours',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='place',
            name='open_hours',
            field=models.TimeField(default='00:00'),
        ),
    ]
