# Generated by Django 3.2 on 2022-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0004_auto_20220908_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='avrg_capacity',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(default='Минск', max_length=20),
        ),
    ]
