# Generated by Django 3.2 on 2022-09-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0005_auto_20220908_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(default='Минск', max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='places', verbose_name='Фото площадки'),
        ),
    ]
