# Generated by Django 3.2 on 2022-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0006_auto_20220908_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='default_place.png', null=True, upload_to='places', verbose_name='Фото площадки'),
        ),
    ]
