# Generated by Django 3.2 on 2022-09-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0010_raiting_raitingplace_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places_app.review', verbose_name='Родитель'),
        ),
    ]
