# Generated by Django 3.2 on 2022-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0015_raitingplace_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отзыва'),
        ),
    ]
