# Generated by Django 3.2 on 2022-09-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0016_review_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
