# Generated by Django 4.1 on 2022-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='User', max_length=20, verbose_name='Автор')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='static', verbose_name='Фото площадки')),
                ('adress', models.CharField(max_length=60, verbose_name='Адрес площадки')),
                ('open_hours', models.TimeField()),
                ('close_hours', models.TimeField(default='00:00')),
                ('kind_sport', models.CharField(blank=True, choices=[('Баскетбол', 'Баскетбол'), ('Волейбол', 'Волейбол'), ('Футбол', 'Футбол')], default='Басктебол', max_length=20, verbose_name='Вид спорта')),
                ('descr', models.TextField(max_length=500, verbose_name='Описание площадки')),
            ],
        ),
    ]
