# Generated by Django 4.1 on 2022-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='User', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static')),
                ('adress', models.CharField(max_length=20)),
                ('Work Hours Field', models.DateTimeField()),
                ('kind_sport', models.CharField(max_length=20)),
                ('descr', models.TextField(max_length=500)),
            ],
        ),
    ]
