# Generated by Django 4.1 on 2022-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='close_hours',
            field=models.TimeField(default='00:00', verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='open_hours',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
