# Generated by Django 4.1 on 2022-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Work Hours Field',
        ),
        migrations.AddField(
            model_name='card',
            name='work_hours',
            field=models.DurationField(blank=True, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='card',
            name='adress',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
