# Generated by Django 4.1 on 2022-08-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0002_remove_card_work hours field_card_work_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='kind_sport',
        ),
    ]
