# Generated by Django 4.1 on 2022-08-27 16:49

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0002_alter_playground_close_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
    ]
