# Generated by Django 4.1 on 2022-08-27 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0003_playground_status_playground_status_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='status',
        ),
        migrations.RemoveField(
            model_name='playground',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='playground',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата в время создания'),
            preserve_default=False,
        ),
    ]
