# Generated by Django 4.1 on 2022-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0003_remove_card_kind_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='kind_sport',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Баскетбол'), (2, 'Волейбол'), (3, 'Футбол')], default=1, verbose_name='Вид спорта'),
        ),
    ]
