# Generated by Django 4.1 on 2022-08-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0004_remove_playground_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='close_hours',
        ),
        migrations.RemoveField(
            model_name='playground',
            name='open_hours',
        ),
    ]
