# Generated by Django 4.1 on 2022-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0005_remove_playground_close_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='name',
        ),
        migrations.AlterField(
            model_name='playground',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата в время создания'),
        ),
    ]
