# Generated by Django 4.1 on 2022-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0007_alter_playground_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
