# Generated by Django 4.1 on 2022-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0008_playground_edit_date_alter_playground_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='User', max_length=20, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='static', verbose_name='Фото площадки')),
            ],
        ),
    ]
