# Generated by Django 4.1 on 2022-08-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0009_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
