# Generated by Django 4.1 on 2022-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0011_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='author',
            field=models.CharField(default='User', max_length=20, verbose_name='Автор'),
        ),
    ]
