# Generated by Django 4.1 on 2022-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0012_mode_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.AddField(
            model_name='playground',
            name='avrg_capacity',
            field=models.CharField(blank=True, choices=[('Баскетбол', 'Баскетбол'), ('Волейбол', 'Волейбол'), ('Футбол', 'Футбол')], default='0-50', max_length=20, verbose_name='Средняя вместимость'),
        ),
        migrations.AddField(
            model_name='playground',
            name='city',
            field=models.CharField(default='Минск', max_length=20, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='playground',
            name='coating',
            field=models.CharField(default='Резиновое', max_length=20, verbose_name='Покрытие'),
        ),
        migrations.AddField(
            model_name='playground',
            name='type_pg',
            field=models.CharField(blank=True, choices=[('Баскетбол', 'Баскетбол'), ('Волейбол', 'Волейбол'), ('Футбол', 'Футбол')], default='Открытый', max_length=20, verbose_name='Тип площадки'),
        ),
    ]
