# Generated by Django 4.1 on 2022-08-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0014_alter_playground_avrg_capacity_alter_playground_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_Radnom_Pg',
        ),
    ]
