# Generated by Django 4.1 on 2022-09-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0015_delete_home_radnom_pg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playground',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
    ]
