# Generated by Django 4.1 on 2022-09-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0016_alter_playground_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playground',
            old_name='image',
            new_name='images',
        ),
    ]
