# Generated by Django 4.1 on 2022-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0017_rename_image_playground_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=60, verbose_name='Адрес площадки')),
                ('kind_sport', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Волейбол', 'Волейбол'), ('Футбол', 'Футбол')], max_length=20, verbose_name='Вид спорта')),
                ('descr', models.TextField(max_length=500, verbose_name='Описание площадки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('type_pg', models.CharField(choices=[('Открытый', 'Открытый'), ('Закрытый', 'Закрытый')], max_length=20, verbose_name='Тип площадки')),
                ('coating', models.CharField(max_length=20, verbose_name='Покрытие')),
                ('avrg_capacity', models.CharField(choices=[('0-50', '0-50 человек'), ('50-100', '50-100 человек'), ('+100', '100+ человек')], max_length=20, verbose_name='Средняя вместимость')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.DeleteModel(
            name='Playground',
        ),
    ]
