# Generated by Django 4.1 on 2022-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_core', '0018_playgrounds_delete_playground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgrounds',
            name='id',
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='adress',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Адрес площадки'),
        ),
    ]
